spring:
  config:
    import:
      classpath:db.yml
  application:
    name: demo
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  mail:
    host: smtp.gmail.com
    port: 587
    username: 0810nayoon@gmail.com
    password: ggedeafqixwrtllx
    properties:
      mail: 
        smtp: 
          auth: true
          starttls: 
            enable: true
server:
  port: 8081
#  servlet:
#    context-path: /test
openai:
  api:
    key: ${OPENAI_API_KEY:your-api-key}
    url: https://api.openai.com/v1/chat/completions
#발급받은 apiKey는 깃허브 업로드시 지우고 업로드하세요 

