spring:
  application:
    name: d
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/DB
    username: "root"
    password: 
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
server:
  port: 8081
#  servlet:
#    context-path: /test
openai:
  api:
    key: ${OPENAI_API_KEY:your-api-key}
    url: https://api.openai.com/v1/chat/completions
#발급받은 apiKey는 깃허브 업로드시 지우고 업로드하세요 
#gitignore에 해당설정파일을 추가하세요